In [1]:
import pandas

In [23]:
parent_folder = 'CTOI Creation'

In [3]:
toi_data = pandas.read_csv('https://exofop.ipac.caltech.edu/tess/download_toi?output=csv')
ctoi_data = pandas.read_csv('https://exofop.ipac.caltech.edu/tess/download_ctoi?output=csv')
koi_data = pandas.read_csv('https://exofop.ipac.caltech.edu/tess/download_koi?sort=koi&output=csv')

toi_data, ctoi_data, koi_data

(         TIC ID      TOI     Previous CTOI  Master  SG1A  SG1B  SG2  SG3  SG4  \
 0     271052158  7461.01               NaN       5     5     5    5    5    5
 1      52368076   125.04               NaN       3     4     3    3    4    4
 2     407126408   913.02               NaN       2     4     2    2    4    4
 3     272840455  7457.01               NaN       5     5     5    5    5    5
 4     251090642  7464.01  TIC 251090642.01       3     4     3    3    4    4
 ...         ...      ...               ...     ...   ...   ...  ...  ...  ...
 7650  438295981   888.01               NaN       5     5     5    5    5    5
 7651  284288080   889.01               NaN       5     5     5    5    5    5
 7652   66561343   892.01               NaN       3     5     5    3    4    4
 7653  123958679   893.01               NaN       3     4     3    3    4    4
 7654  250484865   895.01               NaN       5     5     5    5    5    5

       SG5  ...  Stellar Radius (R_Sun) err  Stellar Metallicity  \
 0       5  ...                    0.062854             0.322043
 1       4  ...                    0.049719                  NaN
 2       4  ...                    0.048844                  NaN
 3       5  ...                         NaN                  NaN
 4       4  ...                    0.015435                  NaN
 ...   ...  ...                         ...                  ...
 7650    5  ...                    0.050000                  NaN
 7651    5  ...                    0.070000                  NaN
 7652    4  ...                    0.040000                  NaN
 7653    4  ...                    0.150000                  NaN
 7654    5  ...                    0.050000                  NaN

       Stellar Metallicity err  Stellar Mass (M_Sun)  Stellar Mass (M_Sun) err  \
 0                    0.012499              0.889000                  0.111650
 1                         NaN              0.910000                  0.110203
 2                         NaN              0.820000                  0.097252
 3                         NaN              1.110000                       NaN
 4                         NaN              0.517765                  0.020273
 ...                       ...                   ...                       ...
 7650                      NaN              1.471000                  0.255432
 7651                      NaN              1.320000                  0.209578
 7652                      NaN              1.820000                  0.307281
 7653                      NaN              2.520000                  0.355635
 7654                      NaN              1.110000                  0.142881

                    Sectors Date TOI Alerted (UTC) Date TOI Updated (UTC)  \
 0     15,40,41,54,55,74,75             2025-06-05             2025-06-05
 1             1,2,28,68,69             2025-06-05             2025-06-05
 2              12,13,65,66             2025-06-05             2025-06-05
 3        41,54,55,56,74,75             2025-06-05             2025-06-05
 4                    47,74             2025-06-05             2025-06-05
 ...                    ...                    ...                    ...
 7650                     6             2019-07-12             2019-07-12
 7651               6,7,8,9             2019-07-12             2020-05-20
 7652                  6,33             2019-07-12             2021-02-19
 7653                  6,33             2019-07-12             2020-05-20
 7654                     6             2019-07-12             2020-05-20

             Date Modified                                           Comments
 0              2025-06-05                                       Kepler-314 c
 1              2025-06-05                   single transit at TBJD  ~ 3188.7
 2              2025-06-05  only two transits 4 years apart; true period l...
 3              2025-06-05                                        Kepler-40 b
 4              2025-06-05                       also a CTOI from Daniel Vogl
 ...                   ...                                                ...
 7650  2022-12-14 12:09:24  A clear centroid shift; signal comes from a bl...
 7651  2022-12-14 12:09:24  blended with something faint; and the matches ...
 7652  2022-12-14 12:09:24                                            TFOP CP
 7653  2022-12-14 12:09:24                                                NaN
 7654  2022-12-14 12:09:24                crowded field; might be variability

 [7655 rows x 62 columns],
           TIC ID          CTOI  Promoted to TOI  MASTER  SG1A  SG1B  SG2  SG3  \
 0          17361  1.736101e+04          3127.01     NaN   NaN   NaN  NaN  NaN
 1         160363  1.603630e+05              NaN     NaN   NaN   NaN  NaN  NaN
 2         592503  5.925030e+05              NaN     NaN   NaN   NaN  NaN  NaN
 3         768070  7.680700e+05              NaN     NaN   NaN   NaN  NaN  NaN
 4         769986  7.699860e+05              NaN     NaN   NaN   NaN  NaN  NaN
 ...          ...           ...              ...     ...   ...   ...  ...  ...
 3734  1961935435  1.961935e+09              NaN     NaN   NaN   NaN  NaN  NaN
 3735  2015243161  2.015243e+09              NaN     NaN   NaN   NaN  NaN  NaN
 3736  2025895835  2.025896e+09              NaN     NaN   NaN   NaN  NaN  NaN
 3737  2040889915  2.040890e+09              NaN     NaN   NaN   NaN  NaN  NaN
 3738  2050290974  2.050291e+09              NaN     NaN   NaN   NaN  NaN  NaN

       SG4  SG5  ... Stellar Eff Temp (K) err Stellar log(g) (cm/s^2)  \
 0     NaN  NaN  ...                  121.637                 4.25352
 1     NaN  NaN  ...                  129.081                 4.15460
 2     NaN  NaN  ...                   70.000                     NaN
 3     NaN  NaN  ...                  125.018                 4.27265
 4     NaN  NaN  ...                  122.000                 4.20725
 ...   ...  ...  ...                      ...                     ...
 3734  NaN  NaN  ...                      NaN                     NaN
 3735  NaN  NaN  ...                  128.000                 4.07962
 3736  NaN  NaN  ...                      NaN                     NaN
 3737  NaN  NaN  ...                  132.842                 4.39699
 3738  NaN  NaN  ...                  369.772                 4.44798

       Stellar log(g) (cm/s^2) err  Stellar Radius (R_Sun)  \
 0                        0.078445                 1.25819
 1                        0.093692                 1.66309
 2                             NaN                 3.23242
 3                        0.072746                 1.23375
 4                             NaN                 1.04351
 ...                           ...                     ...
 3734                          NaN                     NaN
 3735                          NaN                 1.86272
 3736                          NaN                     NaN
 3737                     0.078333                 1.09460
 3738                     0.105034                 1.01643

       Stellar Radius (R_Sun) err         CTOI lastmod       User   Group  \
 0                       0.062226  2020-08-10 07:20:18   montalto     NaN
 1                       0.075980  2021-02-11 04:13:20     steuer     NaN
 2                            NaN  2022-10-20 09:02:36   montalto     NaN
 3                       0.058719  2024-08-28 10:47:42     essack  tfopwg
 4                            NaN  2022-10-20 09:04:55   montalto     NaN
 ...                          ...                  ...        ...     ...
 3734                         NaN  2021-09-07 08:21:56  nardiello     NaN
 3735                         NaN  2021-09-07 08:21:56  nardiello     NaN
 3736                         NaN  2023-10-15 12:57:33      conzo     NaN
 3737                    0.053869  2022-10-20 09:03:27   montalto     NaN
 3738                    0.055942  2022-10-20 09:04:15   montalto     NaN

          Tag                                              Notes
 0      29419                   new CTOI, Montalto et al. (2020)
 1      94179      Found with our in-house single transit finder
 2     420769                          new CTOI, Montalto (2022)
 3     442473  single transit event from the TSTPC working group
 4     421495                          new CTOI, Montalto (2022)
 ...      ...                                                ...
 3734   99732  new CTOI likely member of NGC 7024, PATHOS-81 ...
 3735   99733  new CTOI likely member of NGC 7245, PATHOS-82 ...
 3736  432964          Transit detected from TESS-HUNTER Project
 3737  421032                          new CTOI, Montalto (2022)
 3738  421311                          new CTOI, Montalto (2022)

 [3739 rows x 71 columns],
          TIC ID      TOI    Kepler Name      KOI    KIC ID Disposition  \
 0     399860444  2140.01     Kepler-1 b     1.01  11446443          CP
 1     424865156  1265.01     Kepler-2 b     2.01  10666592          CP
 2      28230919  1144.01     Kepler-3 b     3.01  10748390          CP
 3     377873569  4480.01  Kepler-1658 b     4.01   3861595          CP
 4     159107668  1241.01            NaN     5.01   8554498          PC
 ...         ...      ...            ...      ...       ...         ...
 9559  164999785      NaN            NaN  8293.01  10585887          FP
 9560   26964688      NaN            NaN  8294.01  11867733          FP
 9561   27767095      NaN            NaN  8295.01  11923074          FP
 9562   27318471      NaN            NaN  8296.01  12117215          FP
 9563   27686277      NaN            NaN  8297.01  12168280          PC

       Imaging Observations  Spectroscopy Observations  \
 0                       10                          2
 1                        3                          1
 2                        5                          3
 3                        6                          7
 4                       21                         33
 ...                    ...                        ...
 9559                     0                          0
 9560                     0                          0
 9561                     0                          0
 9562                     0                          0
 9563                     0                          0

       Time Series Observations    RA (deg)  ...  Insolation (Earth flux)  \
 0                            0  286.808526  ...                   761.46
 1                            0  292.247190  ...                  4148.92
 2                            0  297.710176  ...                    96.67
 3                            0  294.356556  ...                  4055.29
 4                            5  289.739730  ...                  1020.05
 ...                        ...         ...  ...                      ...
 9559                         0  285.243335  ...                     1.04
 9560                         0  293.773689  ...                     1.00
 9561                         0  296.140701  ...                   924.14
 9562                         0  294.927920  ...                     1.00
 9563                         0  295.978019  ...                     9.22

       Insolation error  Inclination (deg)  Inclination error  \
 0               106.21              84.41                NaN
 1               651.59              87.21                NaN
 2                14.91              89.82                NaN
 3              1643.78              80.61                NaN
 4               223.43              82.68                NaN
 ...                ...                ...                ...
 9559              0.97              89.94                NaN
 9560              0.86              89.89                NaN
 9561            740.64              89.76                NaN
 9562              0.76              89.98                NaN
 9563              4.18              88.68                NaN

       Planet Radius/Stellar Radius  Planet Rad/Stellar Rad error  \
 0                         0.123871                      0.000051
 1                         0.075522                      0.000298
 2                         0.057823                      0.000351
 3                         0.039601                      0.000521
 4                         0.036574                      0.000154
 ...                            ...                           ...
 9559                      0.014468                      0.004269
 9560                      0.027912                      0.008810
 9561                      0.007608                      0.000483
 9562                      0.025994                      0.000000
 9563                      0.194908                     74.297780

       Stellar Density (g/cm^3)  Stellar Density error  Semi-Major Axis (AU)  \
 0                      1.83538                0.00587                0.0354
 1                      0.37936                0.02846                0.0376
 2                      3.69348                0.02020                0.0530
 3                      0.22463                0.17327                0.0548
 4                      0.34540                0.01415                0.0590
 ...                        ...                    ...                   ...
 9559                   2.11260               47.27140                1.0238
 9560                  10.97445               60.80845                1.0366
 9561                   0.94338                0.06925                0.0277
 9562                  79.41125                0.00000                0.7989
 9563                   0.04708               16.19254                0.8352

       Semi-Major Axis error
 0                       NaN
 1                       NaN
 2                       NaN
 3                       NaN
 4                       NaN
 ...                     ...
 9559                    NaN
 9560                    NaN
 9561                    NaN
 9562                    NaN
 9563                    NaN

 [9564 rows x 35 columns])

In [4]:
toi_data['type'] = 'TOI'
ctoi_data['type'] = 'CTOI'
koi_data['type'] = 'KOI'

columns = ['TIC ID', 'type']

all_planets = pandas.concat([toi_data[columns], ctoi_data[columns], koi_data[columns]], ignore_index = True, sort = False)
all_planets

          TIC ID type
0      271052158  TOI
1       52368076  TOI
2      407126408  TOI
3      272840455  TOI
4      251090642  TOI
...          ...  ...
20953  164999785  KOI
20954   26964688  KOI
20955   27767095  KOI
20956   27318471  KOI
20957   27686277  KOI

[20958 rows x 2 columns]

In [5]:
all_planets = all_planets.drop_duplicates(subset = 'TIC ID', keep = 'first').reset_index(drop = True)
all_planets = all_planets.sort_values(by = 'TIC ID').reset_index(drop = True)

all_planets.to_csv(f'{parent_folder}/Current IDs/all_planets.csv', index = False)

all_planets

           TIC ID  type
0            2876   TOI
1            4711   TOI
2           17361   TOI
3           23111   TOI
4           47667   TOI
...           ...   ...
18264  2016376984   TOI
18265  2025895835  CTOI
18266  2040889915  CTOI
18267  2041563029   TOI
18268  2050290974  CTOI

[18269 rows x 2 columns]

In [19]:
completed_ids = pandas.read_csv(f'{parent_folder}/Current IDs/completed_tic_ids.csv')['ticid'].astype(int)
known_ids = all_planets['TIC ID'].astype(int)

completed_ids, known_ids

(0       16700335
 1       39011225
 2       70999666
 3       73352011
 4       88703412
          ...
 527     47757785
 528     51680439
 529    359675829
 530     63010040
 531     59516000
 Name: ticid, Length: 532, dtype: int64,
 0              2876
 1              4711
 2             17361
 3             23111
 4             47667
             ...
 18264    2016376984
 18265    2025895835
 18266    2040889915
 18267    2041563029
 18268    2050290974
 Name: TIC ID, Length: 18269, dtype: int64)

In [25]:
data_path = f'{parent_folder}/TIC ID Data/tess_tce_80s.csv'
depth = 0.075 * 1e6

In [26]:
data = pandas.read_csv(data_path)
data

,tceid,ticid,tce_plnt_num,sectors,lastUpdate,tce_period,tce_period_err,tce_time0bt,tce_time0bt_err,tce_time0,...,tce_dicco_mdec,tce_dicco_mdec_err,tce_dicco_msky,tce_dicco_msky_err,tce_ditco_mra,tce_ditco_mra_err,tce_ditco_mdec,tce_ditco_mdec_err,tce_ditco_msky,tce_ditco_msky_err
0,00001506919-01,1506919,1,s0080,2024-08-23,0.275020,NaN,3480.02,NaN,2460480.02,...,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000
1,00001506919-02,1506919,2,s0080,2024-08-23,0.824648,NaN,3480.17,NaN,2460480.17,...,-0.877215,2.502889,1.913440,2.503704,1.915084,2.503920,0.266046,2.502888,1.933475,2.503901
2,00002877598-01,2877598,1,s0080,2024-08-23,0.649536,NaN,3479.99,NaN,2460479.99,...,-18.243800,2.501556,34.366810,2.501778,42.104920,2.501838,-10.121050,2.501555,43.304280,2.501823
3,00003473481-01,3473481,1,s0080,2024-08-23,4.713890,NaN,3483.65,NaN,2460483.65,...,-0.405780,2.500181,0.621355,2.500197,-1.532042,2.500206,0.795200,2.500180,1.726121,2.500201
4,00003473481-02,3473481,2,s0080,2024-08-23,12.102500,NaN,3483.34,NaN,2460483.34,...,-0.585337,2.500543,0.587853,2.500543,-1.077392,2.500609,0.571434,2.500541,1.219554,2.500594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,00902810666-01,902810666,1,s0089,2025-03-27,0.660518,0.002932,3718.50,0.002039,2460718.50,...,-0.034121,2.500345,0.135035,2.500301,29.739850,2.500295,-21.500060,2.500341,36.697560,2.500311
16715,00902843385-01,902843385,1,s0089,2025-03-27,20.112500,0.002932,3719.87,0.002039,2460719.87,...,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000
16716,00902843385-02,902843385,2,s0089,2025-03-27,24.312500,0.002932,3721.09,0.002039,2460721.09,...,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000
16717,00902843385-03,902843385,3,s0089,2025-03-27,12.676400,0.002932,3718.55,0.002039,2460718.55,...,19.334970,5.817506,75.454510,5.967508,-27.673600,5.977458,-10.326250,5.817478,29.537430,5.958136
16718,00902843385-04,902843385,4,s0089,2025-03-27,19.200800,0.002932,3723.12,0.002039,2460723.12,...,15.279610,11.877220,76.491720,13.016030,-29.722250,13.061120,-14.455150,11.877210,33.050930,12.843100

In [28]:
data = data[~data['ticid'].isin(completed_ids)]
data = data[~data['ticid'].isin(known_ids)]
data = data[data['tce_depth'] < depth] # any depth
data = data.reset_index(drop = True)

data

,tceid,ticid,tce_plnt_num,sectors,lastUpdate,tce_period,tce_period_err,tce_time0bt,tce_time0bt_err,tce_time0,...,tce_dicco_mdec,tce_dicco_mdec_err,tce_dicco_msky,tce_dicco_msky_err,tce_ditco_mra,tce_ditco_mra_err,tce_ditco_mdec,tce_ditco_mdec_err,tce_ditco_msky,tce_ditco_msky_err
0,00001506919-01,1506919,1,s0080,2024-08-23,0.275020,NaN,3480.02,NaN,2460480.02,...,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000
1,00001506919-02,1506919,2,s0080,2024-08-23,0.824648,NaN,3480.17,NaN,2460480.17,...,-0.877215,2.502889,1.913440,2.503704,1.915084,2.503920,0.266046,2.502888,1.933475,2.503901
2,00003473481-02,3473481,2,s0080,2024-08-23,12.102500,NaN,3483.34,NaN,2460483.34,...,-0.585337,2.500543,0.587853,2.500543,-1.077392,2.500609,0.571434,2.500541,1.219554,2.500594
3,00007851729-01,7851729,1,s0080,2024-08-23,0.626273,NaN,3480.35,NaN,2460480.35,...,0.059860,2.500012,0.215391,2.500006,0.204506,2.500003,0.787360,2.500007,0.813486,2.500006
4,00007851729-02,7851729,2,s0080,2024-08-23,0.313089,NaN,3480.19,NaN,2460480.19,...,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6942,00817523618-03,817523618,3,s0089,2025-03-27,1.690050,0.002932,3718.96,0.002039,2460718.96,...,0.285633,2.500025,0.288309,2.500024,-0.027426,2.500011,0.420776,2.500023,0.421669,2.500023
6943,00841501771-02,841501771,2,s0089,2025-03-27,9.805550,0.002932,3721.64,0.002039,2460721.64,...,-0.044264,2.503504,0.299969,2.503567,-1.238564,2.503567,1.354954,2.503503,1.835740,2.503532
6944,00841501771-03,841501771,3,s0089,2025-03-27,7.744270,0.002932,3722.16,0.002039,2460722.16,...,0.152443,2.500843,0.555939,2.500821,-1.360260,2.500812,1.591074,2.500836,2.093280,2.500826
6945,00875558403-02,875558403,2,s0089,2025-03-27,0.282812,0.002932,3718.25,0.002039,2460718.25,...,-8.998168,2.586988,32.134980,2.598901,-0.273299,2.596464,-0.770207,2.586971,0.817258,2.588034
6946,00902843385-04,902843385,4,s0089,2025-03-27,19.200800,0.002932,3723.12,0.002039,2460723.12,...,15.279610,11.877220,76.491720,13.016030,-29.722250,13.061120,-14.455150,11.877210,33.050930,12.843100

In [29]:
short_data = data[(data['tce_period'] > 10 ** 0.3) & (data['tce_period'] < 10 ** 1)]
short_ids = short_data['ticid'].drop_duplicates().reset_index(drop = True)

short_ids.to_csv(f'{parent_folder}/Current IDs/tic_ids_short_period.csv', index = False)
short_ids

0        7854182
1       32878479
2       41870248
3       48356677
4       48499902
         ...
860    387103691
861    391550834
862    408350711
863    408351795
864    841501771
Name: ticid, Length: 865, dtype: int64

In [30]:
long_data = data[(data['tce_period'] > 10 ** 1) & (data['tce_period'] < 10 ** 1.7)]
long_ids = long_data['ticid'].drop_duplicates().reset_index(drop = True)

long_ids.to_csv(f'{parent_folder}/Current IDs/tic_ids_long_period.csv', index = False)
long_ids

0         3473481
1         9509645
2        14652408
3        20352516
4        28569279
          ...
1031    455278748
1032    808234509
1033    808417644
1034    817099291
1035    902843385
Name: ticid, Length: 1036, dtype: int64